// Auto-generated by GitHub Actions — DO NOT COMMIT
var __ENV__ = {
  apiKey:            "",
  authDomain:        "",
  projectId:         "",
  storageBucket:     "",
  messagingSenderId: "",
  appId:             "",
  vapidKey:          ""
};
