// Auto-generated by GitHub Actions — DO NOT COMMIT
var __ENV__ = {
  apiKey:            "AIzaSyAsQtM429g0MOv-x2d3MK3Kf3UrCeuNGf0",
  authDomain:        "shizennotes.firebaseapp.com",
  projectId:         "shizennotes",
  storageBucket:     "shizennotes.firebasestorage.app",
  messagingSenderId: "1075153875873",
  appId:             "shizennotes.firebaseapp.com",
  vapidKey:          "BNRLNK7rEUSwcjYdHhWJ8BQCjLa9pWgkzDx0LtgCO1trqHyeAhpAUEtQWaeNHqXHJ7Y-QZPzXys4xu-_Ylz9rpo"
};
